---
all:
  children:
    control_plane:
      hosts:
        sidewinder-01:
          ansible_user: "cmdr"
          ansible_host: "192.168.7.11"
        sidewinder-02:
          ansible_user: "cmdr"
          ansible_host: "192.168.7.12"
        sidewinder-03:
          ansible_user: "cmdr"
          ansible_host: "192.168.7.13"

    workers:
      hosts:
        sidewinder-04:
          ansible_user: "cmdr"
          ansible_host: "192.168.7.14"
        sidewinder-05:
          ansible_user: "cmdr"
          ansible_host: "192.168.7.15"
        sidewinder-06:
          ansible_user: "cmdr"
          ansible_host: "192.168.7.16"
        sidewinder-07:
          ansible_user: "cmdr"
          ansible_host: "192.168.7.17"
        sidewinder-08:
          ansible_user: "cmdr"
          ansible_host: "192.168.7.18"
        sidewinder-09:
          ansible_user: "cmdr"
          ansible_host: "192.168.7.19"

    k8s_nodes:
      children:
        control_plane:
        workers:

    nfs:
      hosts:
        hauler-mkiii:
          ansible_user: "CMDR"
          ansible_host: "192.168.7.7"
