---
- name: Create argocd namespace
  become: true
  ansible.builtin.shell: |
    kubectl create namespace argocd \
      --dry-run=client -o yaml | kubectl apply -f -
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Add Argo Helm repository
  become: true
  kubernetes.core.helm_repository:
    name: argo
    repo_url: https://argoproj.github.io/argo-helm

- name: Install ArgoCD HA using Helm
  become: true
  kubernetes.core.helm:
    name: argocd
    chart_ref: argo/argo-cd
    chart_version: 8.3.4
    release_namespace: argocd
    create_namespace: false
    wait: true
    timeout: 15m
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Wait for ArgoCD deployment rollout
  become: true
  command: >
    kubectl rollout status deployment/argocd-server
    --namespace=argocd
    --timeout=900s
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  register: rollout_result
  changed_when: false

- name: Show kubectl rollout output
  ansible.builtin.debug:
    var: rollout_result.stdout_lines

- name: Download infrastructure-project.yaml to remote host
  become: true
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/CMDR-JohnAlex/sidewinder-cluster-gitops/main/bootstrap/projects/infrastructure.yaml
    dest: /tmp/argocd/infrastructure-project.yaml
    mode: '0644'

- name: Create infrastructure project
  become: true
  ansible.builtin.command:
    cmd: kubectl apply -f /tmp/argocd/infrastructure-project.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  register: argocd_bootstrap

- name: Download root-app.yaml to remote host
  become: true
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/CMDR-JohnAlex/sidewinder-cluster-gitops/main/bootstrap/root-app.yaml
    dest: /tmp/argocd/bootstrap.yaml
    mode: '0644'

- name: Bootstrap GitOps
  become: true
  ansible.builtin.command:
    cmd: kubectl apply -f /tmp/argocd/bootstrap.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  register: argocd_bootstrap

- name: Show kubectl output
  ansible.builtin.debug:
    var: argocd_bootstrap.stdout_lines
