---
- name: Install Kubernetes apt key
  become: true
  ansible.builtin.shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.36/deb/Release.key \
      | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes apt repository
  become: true
  ansible.builtin.deb822_repository:
    name: kubernetes
    types:
      - deb
    uris:
      - https://pkgs.k8s.io/core:/stable:/v1.36/deb/
    suites:
      - /
    signed_by: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    state: present

- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: true
